apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: image-data-pvc
  namespace: cv-platform
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 50Gi
  storageClassName: standard
